module StoreHours
  # When parslet apply the TreeTransformer to the intermediary tree generated by parser,
  # it may raise this exception if the input is valid syntax-wise but contains errors.
  #
  # Possible scenarios to cause this exception are defined in tree_transformer.rb.
  #
  class SemanticError < StandardError
    def initialize(message)
      super(message)
    end
  end
end