module StoreHours
  # When parslet apply the TreeTransformer to the intermediary tree generated by parser,
  # it may raise this exception if the input is valid syntax-wise but contains errors.
  #
  # Two possible scenarios:
  #   1. ending day is earlier than starting day, for example,
  #       "fri-mon" is not a valid
  #   2. ending time is earlier than starting time, for example,
  #       "9:00pm-10:00am" is not valid
  #
  # Use the @message attribute if you need to show friendly error message.
  class SemanticError < StandardError
    def initialize(message)
      super(message)
    end
  end
end